### ISSUE TITLE
Problems to run Glide demo with default environment

### ISSUE THREAD

**Issue by charlesxu90** [MolecularAI/DockStreamCommunity#2]
Hello, I tried to run the Glide demo, however, the demo calls Corina during Ligand Preparation. Why not using the defult ligprep from Schrodinger? Any hints on how to solve this? 

``` python
File "/home/xiaopeng/Desktop/DockStream/dockstream/core/Corina/Corina_ligand_preparator.py", line 59, in __init__
    raise LigandPreparationFailed("Cannot initialize Corina backend - abort.")
dockstream.utils.dockstream_exceptions.LigandPreparationFailed: Cannot initialize Corina backend - abort.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaopeng/Desktop/DockStream/docker.py", line 132, in <module>
    raise LigandPreparationFailed
dockstream.utils.dockstream_exceptions.LigandPreparationFailed
```

**Comment by charlesxu90** [comment]
Tried with the following config file, but it still pops up an error
``` python
glide_ligprep_conf_json = {
  "docking": {
    "header": {                                   # general settings
      "environment": {
      }
    },
    "ligand_preparation": {                       # the ligand preparation part, defines how to build the pool
      "embedding_pools": [
        {
          "pool_id": "Ligprep",
          "type": "Ligprep",
          "parameters": {
            "prefix_execution": "module load schrodinger/2019-4",
            "use_epik": {
                "target_pH": 7.4,                 # LigPrep embeds ligands at a specified pH which is particularly
                "pH_tolerance": 0.2               # relevant to ionization states --> this parameter can be tweaked
          },
            "force_field": "OPLS3e"
          },
          "input": {
            "standardize_smiles": False,
            "input_path": smiles_path,
            "type": "smi"                                   
          }
        }
      ]
    },
    "docking_runs": [
        {
          "backend": "Glide",
          "run_id": "Glide",
        "input_pools": ["Ligprep"],
        "parameters": {
          "prefix_execution": "module load schrodinger/2019-4", # will be executed before a program call
          "parallelization": {                                  
            "number_cores": 2
          },
          "glide_flags": {                                  # all all command-line flags for Glide here 
            "-HOST": "localhost"
          },
          "glide_keywords": {                               # add all keywords for the "input.in" file here
            "EXPANDED_SAMPLING": "True",                    # all these parameteres can be tweaked and/or
            "GRIDFILE": [glide_grid_path],                  # included/omitted
            "NENHANCED_SAMPLING": "2",
            "POSE_OUTTYPE": "ligandlib_sd",
            "POSES_PER_LIG": "3",
            "POSTDOCK_NPOSE": "15",
            "POSTDOCKSTRAIN": "True",
            "PRECISION": "HTVS"
          }
        },
        "output": {
          "poses": { "poses_path": glide_docked_poses_path },            # output path to save docked poses
          "scores": { "scores_path": glide_docked_scores_path }          # output path to save docked scores   
        }
      }
    ]
  }
}

```

**Comment by charlesxu90** [comment]
> Tried with the following config file, but it still pops up an error
> 
> ```python
> glide_ligprep_conf_json = {
>   "docking": {
>     "header": {                                   # general settings
>       "environment": {
>       }
>     },
>     "ligand_preparation": {                       # the ligand preparation part, defines how to build the pool
>       "embedding_pools": [
>         {
>           "pool_id": "Ligprep",
>           "type": "Ligprep",
>           "parameters": {
>             "prefix_execution": "module load schrodinger/2019-4",
>             "use_epik": {
>                 "target_pH": 7.4,                 # LigPrep embeds ligands at a specified pH which is particularly
>                 "pH_tolerance": 0.2               # relevant to ionization states --> this parameter can be tweaked
>           },
>             "force_field": "OPLS3e"
>           },
>           "input": {
>             "standardize_smiles": False,
>             "input_path": smiles_path,
>             "type": "smi"                                   
>           }
>         }
>       ]
>     },
>     "docking_runs": [
>         {
>           "backend": "Glide",
>           "run_id": "Glide",
>         "input_pools": ["Ligprep"],
>         "parameters": {
>           "prefix_execution": "module load schrodinger/2019-4", # will be executed before a program call
>           "parallelization": {                                  
>             "number_cores": 2
>           },
>           "glide_flags": {                                  # all all command-line flags for Glide here 
>             "-HOST": "localhost"
>           },
>           "glide_keywords": {                               # add all keywords for the "input.in" file here
>             "EXPANDED_SAMPLING": "True",                    # all these parameteres can be tweaked and/or
>             "GRIDFILE": [glide_grid_path],                  # included/omitted
>             "NENHANCED_SAMPLING": "2",
>             "POSE_OUTTYPE": "ligandlib_sd",
>             "POSES_PER_LIG": "3",
>             "POSTDOCK_NPOSE": "15",
>             "POSTDOCKSTRAIN": "True",
>             "PRECISION": "HTVS"
>           }
>         },
>         "output": {
>           "poses": { "poses_path": glide_docked_poses_path },            # output path to save docked poses
>           "scores": { "scores_path": glide_docked_scores_path }          # output path to save docked scores   
>         }
>       }
>     ]
>   }
> }
> ```

After comment out the "prefix_execution" lines, it runs. The return is shown below.

Running Glide_LigPrep
CompletedProcess(args=['~/miniconda3/envs/DockStream/bin/python ~/Desktop/DockStream/docker.py -conf ~/Desktop/Benchmarking_demo/benchmarking_conf_jsons/Glide_LigPrep.json -debug'], returncode=0, stdout='', stderr='')

**Comment by charlesxu90** [comment]
The default demo has 15 SMILES. and the `"POSES_PER_LIG"` param is set to be `"3"`.  So it should have 45 docking results in the csv file.

However, what confuses me is that the number of docking results does not match with the expected number. The docking results has 34 lines in the CSV, while it should have 45. 

Several ligands have 3 lines, while others not. Ligand 4 even not appear in the docking results. 

Any explanations for this?

**Comment by GuoJeff** [comment]
Hi @charlesxu90,

In the Glide demo, Corina was used as the ligand embedder to show that DockStream is flexible in using different combinations of ligand embedders + docking backends. 

In the benchmarking demo, the default pairing of Glide + LigPrep is used. The `"POSES_PER_LIG"` parameter is a Glide keyword that sets the maximum number of returned poses. However, it doesn't guarantee that Glide returns the requested number of poses if it doesn't find enough favourable and distinct poses. Poses may also not be returned at all if no favourable ones are found. The benchmarking demo was strictly to showcase that DockStream can automate sequential docking executions. To improve Glide performance, an example first step would be to change the `"PRECISION"` keyword from the current `"HTVS"` to `"SP"`. This would enforce Glide to perform a more exhaustive poses search and may return more poses at the cost of longer computation time.
